version: '3.8'

services:
  backend:
    build: ./backend
    container_name: blogify-backend
    ports:
      - '4000:4000'
    volumes:
      - ./data:/data

  frontend:
    build: .
    container_name: blogify-frontend
    ports:
      - '3000:80'
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://backend:4000
