apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: 835175800383.dkr.ecr.us-east-1.amazonaws.com/blogify-backend:latest
          ports:
            - containerPort: 4000
          env:
            - name: REDIS_HOST
              value: 'redis'
            - name: REDIS_PORT
              value: '6379'
          envFrom:
            - secretRef:
                name: blogify-secret
            - configMapRef:
                name: blogify-config
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: backend-pvc
