apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      serviceAccountName: blogify-backend-sa
      containers:
        - name: backend
          image: 835175800383.dkr.ecr.us-east-1.amazonaws.com/blogify-backend:latest
          ports:
            - containerPort: 4000
          envFrom:
            - configMapRef:
                name: blogify-config
            - secretRef:
                name: blogify-secret
          env:
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: blogify-redis-secret
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name: blogify-redis-secret
                  key: REDIS_PORT
